site:
  title: Nvidia Accelerator Configuration for Scale
  start_page: maas-gpu-enablement::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
